global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blinkmarket-keeper'
    static_configs:
      - targets: ['keeper:9090']
        labels:
          service: 'keeper'
          environment: 'production'
